name: pipeline
on:
  push:
    branches:
      - main

jobs:
  Informacion:
    runs-on: 	windows-latest
    steps:
      - name: Fecha
        run: date
      - name: Control
        uses: actions/checkout@v4
      - name: Repo-Actual  
        run: echo "🔎 Rama=> ${{ github.ref }} Repo=> is ${{ github.repository }}."
        
  AsignarJDK:
    runs-on: 	windows-latest
    steps:
       - name: Control
         uses: actions/checkout@v4
       - name: Set up JDK 16
         uses: actions/setup-java@v3
         with:          
            java-version: '16'
            distribution: 'temurin'
            cache: maven
       - run: echo "JDK asignada"
    
  ValidaPom:
      runs-on: 	windows-latest
      steps:
       - name: Control
         uses: actions/checkout@v4
       - name: Validar
         run: mvn validate
   
      

