name: pipeline
on:
  push:
    branches:
      - main

jobs:
  Compilacion:
    runs-on: 	windows-latest
    steps:
      - name: Chequear
        uses: actions/checkout@v4
      - name: Compilar Java  
        run: |
          echo "Compilando Aplicacion"
          mvn compile
